### ISSUE TITLE
where to store private keys?

### ISSUE THREAD

**Issue by hoosierEE** [eecs280staff/autograder-sandbox#36]
My goal is to `git clone` a private repo from GitHub.
Currently I'm storing my private keys in the repo*.

In my course Dockerfile, I have these lines:

```Dockerfile
RUN mkdir -p /root/.ssh
COPY mykey /root/.ssh/id_rsa
COPY mypub /root/.ssh/id_rsa.pub
```

This lets me `git clone` the teacher repo at build time (good).
I also want to `git clone` at run-time, when the student submits their work and a test suite runs in the container.

Where should I put ssh keys so the container can `git clone` a private repo at run-time?

\* I know this is not ideal, as anyone in the docker group on the server can accidentally publish this image to docker hub, so if you have a nice workaround I'm all ears.

**Comment by james-perretta** [comment]
Your commands will be run as the "autograder" user, so I think you'll want to put them in /home/autograder/.ssh

Let's continue this discussion over email if you don't mind. You can reach me at help@autograder.io. Thanks!
