### ISSUE TITLE
How to increase number of processes during "setup" step?

### ISSUE THREAD

**Issue by hoosierEE** [eecs280staff/autograder-sandbox#37]
I'm trying to run a `make` command in the setup phase of a test suite, and get this:

```
make: fork: Resource temporarily unavailable
--
21 | /bin/sh: 1: Cannot fork
```

Is that due to a process limit? Can I increase the limit somehow?

**Comment by james-perretta** [comment]
For setup commands, the process limit is automatically set to the maximum allowed. I don't know what that number is for your deployment, so you'll have to get in touch with Andrew Lukefahr to find out. 

Let's continue this discussion over email (help@autograder.io). Thanks again!
